language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "22"
script:
    - npm run build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: main
  commit_message: "Deploy Release"
  on:
    branch: main