language: node_js
node_js:
  - "22"
cache:
  directories:
    - ~/.npm
git:
  depth: 3

script:
  - npm install
  - npm run build
  - rm -rf docs
  - mkdir docs
  - cp -r dist/* docs/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  target-branch: main
  on:
    branch: main
