language: node_js
node_js:
  - "22"

cache:
  directories:
    - ~/.npm

install:
  - npm install

script:
  - npm run deploy

deploy:
  provider: script
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  script: npm run deploy # Ejecuta el script de despliegue (gh-pages)
  on:
    branch: main
