language: node_js
node_js:
  - "22"

cache:
  directories:
    - ~/.npm

install:
  - npm install

script:
  - npm run build
  - rm -rf docs
  - mv dist docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: main
